# Generated by Django 5.0 on 2024-09-07 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ladies', 'ladies'), ('gents', 'gents'), ('boys', 'boys'), ('girls', 'girls'), ('kids', 'kids')], max_length=50)),
                ('sub_cateory', models.CharField(choices=[('sandals', 'sandals'), ('slipper', 'slipper'), ('flipflops', 'flipflops'), ('casualshoes', 'casualshoes'), ('flatshoes', 'flatshoes'), ('schooledition', 'schooledition'), ('shoes', 'shoes')], max_length=50)),
                ('new_arrival', models.BooleanField(default=False)),
                ('handmade_and_fastive', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='product_images')),
                ('available', models.BooleanField(default=True)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offer_percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('offer_is_available', models.BooleanField(default=False)),
                ('quantity', models.CharField(blank=True, default=1, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileIphoto', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=225, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.TextField(blank=True, max_length=100, null=True)),
                ('streetaddress', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_color', models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Camel', 'Camel'), ('Cherry', 'Cherry'), ('Gold', 'Gold'), ('Grape', 'Grape'), ('Green', 'Green'), ('Grey', 'Grey'), ('Maroon', 'Maroon'), ('Mehandi', 'Mehandi'), ('Navy', 'Navy'), ('Olive', 'Olive'), ('Peach', 'Peach'), ('Peacock', 'Peacock'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Tan', 'Tan'), ('Violet', 'Violet'), ('White', 'White'), ('Wine', 'Wine'), ('Yellow', 'Yellow'), ('sky blue', 'sky blue'), ('fblack', 'fblack'), ('Lemon', 'Lemon')], max_length=100)),
                ('image', models.ImageField(upload_to='product_images_colors')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='volantapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volantapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offer_percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('offer_is_available', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='volantapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ManyToManyField(through='volantapp.CartItem', to='volantapp.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volantapp.usercart'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('order-placed', 'Order Placed'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='pending', max_length=50)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volantapp.color')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volantapp.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volantapp.size')),
            ],
            options={
                'unique_together': {('user', 'product', 'color', 'size', 'status')},
            },
        ),
    ]
